version: '3'

services:
  mqtt:
    image: emqx/emqx
    container_name: mqtt
    ports:
      - 1883:1883
    restart: always

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - /var/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - monitoring_prometheus
      - influxdb
    ports:
      - 3000:3000
    restart: always

  mqtt_broker:
    image: mqtt_broker
    container_name: mqtt_broker
    depends_on:
      - mqtt
      - influxdb
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: always
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor

  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: always
    ports:
      - 8080:8080
  # mqtt_debug:
  #   image: mqtt_debug
  #   container_name: mqtt_debug
  #   restart: always
